### ISSUE TITLE
Replit sample code

### ISSUE THREAD

**Issue by joerenteria** [learn-co-curriculum/phase-0-pac-2-logging-in-javascript#1]
console.log('Hello, world!');

This is not added by default upon opening replit

**Comment by graciemcguire** [comment]
Hi @joerenteria, repl.it is an external site and is not maintained by the Flatiron curriculum team. 

If you're still having troubles, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
